# Generated by Django 3.2.19 on 2023-05-18 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataelement',
            name='Program',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.program'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='indicator',
            name='Program',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.program'),
            preserve_default=False,
        ),
    ]
