# Generated by Django 3.2.19 on 2023-05-18 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20230518_0933'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dataelement',
            old_name='Program',
            new_name='program',
        ),
        migrations.RenameField(
            model_name='indicator',
            old_name='Program',
            new_name='program',
        ),
    ]
