# Generated by Django 3.2.19 on 2023-05-18 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20230518_0942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataelement',
            name='name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='name',
            field=models.CharField(max_length=500),
        ),
    ]
